### ISSUE TITLE
while implementing ngx-wow in your way its not working there is no error but wow is also not running 

### ISSUE THREAD

**Issue by QuestionDoubt** [tinesoft/ngx-wow#14]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by tinesoft** [comment]
Hi @QuestionDoubt 

Can you provide at least the info mentioned in the issue template?
Without those minimum info, i cannot help you much.. :(
Also, what is your setup? are you using angular CLI or another starter?

**Comment by tinesoft** [comment]
Hi,

I have indeed forgot to mention in the docs that "wowjs" (which is a peerDependency of this lib) must be installed as well as dependencies of your app (sorry :( )

npm install --save wowjs

I will update the documentation shortly.

Thanks for reporting!
