### ISSUE TITLE
Method pipe for use method filter

### ISSUE THREAD

**Issue by mateusneves** [tinesoft/ngx-wow#22]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### OS and Version?
macOS Yosemite

### Versions
Angular CLI: 7.0.3
Node: 10.8.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.3
@angular-devkit/core         7.0.3
@angular-devkit/schematics   7.0.3
@schematics/angular          7.0.3
@schematics/update           0.10.3
rxjs                         6.3.3
typescript                   3.1.3

### Repro steps
I needed to use the pipe method to be able to use the filter method, because if I did not use the pipe, the angle would always return an implementation error of the filter method.

So in the end for the wow operation, I had to apply the filter in the constructor as follows:

this.router.events.pipe(filter(event => event instanceof NavigationEnd)).subscribe(event => {
      // Reload WoW animations when done navigating to page,
      // but you are free to call it whenever/wherever you like
      this.wowService.init(); 
});

**Comment by tinesoft** [comment]
Hi @mateusneves 

I'm sorry, i don't really understand what you want here... 😟
 Can you elaborate? What exactly is the issue? what solution are you proposing?

Thanks

**Comment by tinesoft** [comment]
Closed due to inactivity
